export const THEME = {
  colors: {
    primary: '#FF4B0A', // Laranja clássico do Delphi
    primaryDark: '#E03E00',
    primaryLight: '#FFF0EB',
    background: '#F4F6F9',
    card: '#FFFFFF',
    cardLight: '#F8FAFC',
    inputBackground: '#F8FAFC',
    inputBorder: '#E2E8F0',
    inputBorderFocus: '#FF4B0A',
    textPrimary: '#1E293B',
    textSecondary: '#64748B',
    textMuted: '#94A3B8',
    border: '#E2E8F0',
    borderLight: '#F1F5F9',
    success: '#16A34A',
    successLight: '#DCFCE7',
    warning: '#D97706',
    warningLight: '#FEF3C7',
    danger: '#DC2626',
    dangerLight: '#FEE2E2',
    white: '#FFFFFF',
    black: '#0F172A',
  },
  borderRadius: {
    xs: 6,
    sm: 8,
    md: 10,
    lg: 14,
    xl: 18, // Padrão XRadius do Delphi
    full: 9999,
  },
  shadows: {
    card: {
      shadowColor: '#0F172A',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.04,
      shadowRadius: 6,
      elevation: 2,
    },
    floating: {
      shadowColor: '#FF4B0A',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.28,
      shadowRadius: 12,
      elevation: 6,
    },
    button: {
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.12,
      shadowRadius: 6,
      elevation: 3,
    },
  },
};
